spring:
  datasource:
    url: jdbc:postgresql://dpg-ci7akq98g3nfucdt3ku0-a.frankfurt-postgres.render.com/hits_user_service_db
    username: admin
    password: pPMJlvwImRXVEdB5NCWdv3wX8l3CI8i8

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  jackson:
    serialization:
      fail-on-empty-beans: false

